### ISSUE TITLE
When creating a note from selection, check if it contains a TODO and use the comment as text

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#1]
When creating a note from selection, check if it contains a TODO and use the comment as text (as the place holder text).

**Comment by drishit96** [comment]
Hi @thamara, I would like to work on this

**Comment by thamara** [comment]
Great! I've assigned the issue to you.
Let me know if you need more informations.

**Comment by drishit96** [comment]
Do you want the annotation text to be the same as the TODO? So that  when user presses enter without filling anything, the  TODO text will get saved as the annotation?

**Comment by thamara** [comment]
Yes. My idea is that, if the user is selecting a portion of the code that includes a TODO, most likely is that TODO content that they want. So the idea is to prefill the text area for the description with that text, and, if the user hits enter, that text will be user. This way if the user still wants to add some other text, it's possible.
