### ISSUE TITLE
Create an icon for the extension

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#13]
We have an icon for the extension, but it's not pretty and gets really nasty on the activity bar:

![image](https://user-images.githubusercontent.com/846063/95005968-14cbb700-05d5-11eb-8bf4-05a628a9ef90.png)
![image](https://user-images.githubusercontent.com/846063/95005986-3d53b100-05d5-11eb-97ad-ba2ca13c6c17.png)

We need a new icon, and one version of such icon just with lines.

**Comment by m1ga** [comment]
how about combining them and remove the outer part? Something like this:

![image](https://user-images.githubusercontent.com/4334997/95012342-19758700-0638-11eb-8359-8039fd3c9421.png)

**Comment by BarbaraAlmeida** [comment]
I've sketched some ideas:
![annotation_extension_icon_ideas](https://user-images.githubusercontent.com/10374661/95018510-956ecf80-0636-11eb-9b34-3ecbbe61428b.png)

Anything that you're interested in seeing on vector?

**Comment by BarbaraAlmeida** [comment]
Going a bit more abstract (aka crazier) with the sticky notes idea:
![annotation_extension_icon_ideas_2](https://user-images.githubusercontent.com/10374661/95023441-6c106c80-0653-11eb-89e8-fdddf675a58f.png)

**Comment by thamara** [comment]
Thank you @BarbaraAlmeida  and @m1ga for your suggestions. I really liked the more abstract feel of one of Barbara's suggestions.
I liked the colorful "plus sign", maybe with a "cut" for something that would look like a comment. Something like:

![image](https://user-images.githubusercontent.com/846063/95025320-32ddf980-065f-11eb-8c47-2bd035155dbd.png)

Barbara, would you be willing to work on that?

**Comment by BarbaraAlmeida** [comment]
Sure, I'm working on it.

Just 2 attention points:

* With the + sign logo the sticky notes are smaller to the cuts may be too small, but I'll work on a feel variations and we can test it.
* I've noticed afterwards that the + version looks a bit like slack icon:
![image](https://user-images.githubusercontent.com/10374661/95146796-3a7fca00-0755-11eb-99c5-0a424f907bea.png)
Not too close but I wanted to let you know.

**Comment by thamara** [comment]
I haven't noticed that! Maybe because the icon I'm used to see is within a white bg hahahah
But I still think it's different enough, especially because of the harder edges on the "post it tags".

**Comment by BarbaraAlmeida** [comment]
Before adding colors and the cuts, here are some options for the proportion of the sticky notes:
![annotation_icon_proportions_1](https://user-images.githubusercontent.com/10374661/95147611-9a777000-0757-11eb-90a8-df0ec2cd5fab.png)
![annotations_icon_proportions_2](https://user-images.githubusercontent.com/10374661/95147612-9ba89d00-0757-11eb-9b55-8e609c28d833.png)
![annotations_icon_proportions_3](https://user-images.githubusercontent.com/10374661/95147613-9c413380-0757-11eb-9e54-dbf015573c53.png)
![annotations_icon_proportions_4](https://user-images.githubusercontent.com/10374661/95147615-9cd9ca00-0757-11eb-81f3-3e623379c6fc.png)
What do you prefer @thamara  (you can also choose something in between)?
Also, what do you think of how close they are of each other?

**Comment by thamara** [comment]
I think the first options looks better. It looks like it fills the square space better.

Regarding the space between each other, I think the one you have on the mockup looks pretty good already. Considering a smaller icon, around 48-ish px, maybe it's worth to make them a little apart, but I cannot really judge that now. I believe you can judge that :)

**Comment by m1ga** [comment]
Those look like a Playstation D-Pad if you arrange them like this. They even have almost the same colors for the buttons so when people see that icon they'll think of a Playstation extension :)

**Comment by thamara** [comment]
Some more ideas:

![image](https://user-images.githubusercontent.com/846063/95401722-5c5b8700-08e4-11eb-9a64-a9cb228b88a8.png)

**Comment by thamara** [comment]
@m1ga I could not unseen the Playstation symbol hahahahah
Thanks for this feedback.
I was talking with @BarbaraAlmeida and we converged into an icon that is a mix of the indication post its with a file:

![image](https://user-images.githubusercontent.com/846063/95405699-de50ad80-08ee-11eb-8d6c-384754d11e8e.png)

**Comment by BarbaraAlmeida** [comment]
I can't unsee it either 😅

Here's the result of our brainstorm from yesterday:
![image](https://user-images.githubusercontent.com/10374661/95524220-27fccf00-09a7-11eb-9d84-11d7e5f1378b.png)

**Comment by thamara** [comment]
LOVED IT!

**Comment by thamara** [comment]
To publish a PR, you'll need to add the icons to `resources`, replacing the icons that existed there. If you keep the same name, you won't need to do anything else.
