### ISSUE TITLE
When editing the item, add the text to the input box

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#2]
When editing the item, add the text to the input box. Currently, the text area that opens is empty.

**Comment by StellaJung-Student** [comment]
Hello, can I try to this? Please assign to me~

**Comment by thamara** [comment]
Sure! Thanks!

**Comment by StellaJung-Student** [comment]
I tried to run the test and it gave me this errors.
![image](https://user-images.githubusercontent.com/59578350/95004877-096d9100-05bf-11eb-9ebe-78706f6f8690.png)
When you run the test, are there any errors?
And, please guide me how I can reproduce the bug?
I tried it, but it is hard:)

**Comment by thamara** [comment]
We don't have any tests yet, so running it most likely have its issue.
To reproduce this issue you can follow the instructions to run on vscode and on the new window with the extension do the following:
- Add a new plain note the command pallete: Ctrl + Shift + P > "Code Annotation: Add Plain Note
![image](https://user-images.githubusercontent.com/846063/95004940-79cce000-05c8-11eb-8c2a-877082a76647.png)

- Give it some text and hit Enter:
![image](https://user-images.githubusercontent.com/846063/95004950-9406be00-05c8-11eb-85c8-7e3ae2eff5c8.png)

- Clicking on the item on the Code Annotation pane, will show the Edit Menu:
![image](https://user-images.githubusercontent.com/846063/95004957-aaad1500-05c8-11eb-8249-92e5508adf4d.png)

This will make a new input text to be open for the new text to be entered. This new text will be empty, and the idea is to have the text from the original item.

**Comment by thamara** [comment]
#15 Might be useful here.

**Comment by thamara** [comment]
@StellaJung-Student any updates on this?

**Comment by thamara** [comment]
Hi @StellaJung-Student , since we got no news in a while I'll remove the assignee. If you intend on work on this yet, let me know.

**Comment by StellaJung-Student** [comment]
@thamara I think I am no longer able to finish this~ I will let someone else continue~

**Comment by thamara** [comment]
That's ok @StellaJung-Student. Thank you for letting me. Hope to see you around :)

**Comment by taismassaro** [comment]
@thamara I saw this one was free and created a PR to feel better about not being able to figure out the other one tonight, hope that's ok 😬

**Comment by thamara** [comment]
That's totally ok! Thank you very much for all the help!
