### ISSUE TITLE
Allow for customization of TODO keywords to match when prefilling add note

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#20]
In #15 a check was added to see if the selection used to create a note contains `\\ TODO: `, which is a very used way of commenting, but we can do better.
The idea is to include more regexp to try to match, for example:

- `//TODO:` (no space between // and TODO)
- `// FIX:`
- Support other comments such as `# ...`

The idea is to have this as a configuration, and the users can set what are the strings they want to match.

Project Manager, has an example of a configuration style I think would be great for this:

![image](https://user-images.githubusercontent.com/846063/95030833-b6601080-0688-11eb-8770-8e6fca574e25.png)

**Comment by Jack073** [comment]
I can modify the regex to work with some common ones like the ones you mentioned there, is that something you'd merge for now?
