### ISSUE TITLE
Pending and Done items on tree should have different menu options than general items

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#21]
Pending and Done items on tree should have different menu options than general items. Currently, we show:

![image](https://user-images.githubusercontent.com/846063/95035197-aea96780-069a-11eb-8992-d0362ea1c23f.png)

It should be:
- Check all (for Pending)
- Uncheck all (for Done)
- Remove all (for both)

To achieve this I believe we need to create a new "view", similar to what we do for $PendingNote and $CompleteNote, tag the type on NoteItem using `contextValue`, and specifying rule on `package.json`.

**Comment by thamara** [comment]
Wait until #22 is merged as it can be reused for this request.

**Comment by ftonato** [comment]
After merge #22 we can rename this issue for "remove all items from menu" as a feature request and assign it to me.

**Comment by thamara** [comment]
@ftonato Your PR already fixed part of the problem, but it would be really nice to have the following options under the drop down menu (besides the icon on the item):

- Check all (for Pending)
- Uncheck all (for Done)
- Remove all (for both)

@ftonato would you be interested in working on this remaining task?

**Comment by ftonato** [comment]
Hello,

I don't know if you're doing A / B testing to see which approach will be used the most, but I'll give you my 50 cents:

- You already have the behavior available through the icons for each MENU ITEM (these three behaviors) that is clear to everyone.

Your suggestion is to add another "level" to do the same, we will copy the same behavior, but now the user needs to click one extra time (first click = open "options", the second click = "do what you can do without clicking to open options ")

This desire seems redundant. It is like creating a back button on websites when we already have the menu button "always available".

I am not judging your work, I appreciate your effort and contribute as a form of thanks, but I would like to suggest A / B tests to avoid "wasting time doing things that no one will use"

Do you want this feature? If yes, assign it to me, and I'll pickup it.

**Comment by thamara** [comment]
@ftonato That's a very good point, and something that I haven't really put much thought into. Thanks for pointing that out. I have no formal instruction at all in UX, so sometimes this might happen.
But thankfully open source exists and people like you can come with great ideas!
