### ISSUE TITLE
Remove button does not make sense for pending/done items

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#30]
Pending and Done items on the view have the "Remove Note" button, which doesn't make sense for those as they are aggregators of items and already have the "Remove All Notes".

The second button on the first line is the one to be removed:
![image](https://user-images.githubusercontent.com/846063/96846262-0a5c4a80-1428-11eb-8d04-f018c8808a4d.png)

**Comment by smsriharsha** [comment]
@thamara I have fixed the remove note button. please check and merge #32.
