### ISSUE TITLE
Review icons for check/uncheck all

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#31]
Review icons for check/uncheck all

**Comment by thamara** [comment]
@BarbaraAlmeida Would be interested in that?

**Comment by BarbaraAlmeida** [comment]
I am

**Comment by BarbaraAlmeida** [comment]
I actually liked the check/uncheck all icons 😅
So my first approach was to try to make them more consistent witht the other ones and I've noticed it lacked consistency overall.
So I've played a bit with all of them.

![annotation_icons](https://user-images.githubusercontent.com/10374661/97097628-7241a980-1651-11eb-9972-7595f49c6623.png)

What do you think?

**Comment by BarbaraAlmeida** [comment]
The is a mistake on my notes, actually done has an icon an it's the same as the check note.
I would have it as a checked box to be consistent with the unchecked box, but that's already what I've proposed for the check note icon.

**Comment by thamara** [comment]
I really liked those! Awesome work!
My only concern with having the check/uncheck note with the box is that maybe this will make the interface a bit polluted.
We have the icons on the notes themself (on the left-hand side), and we need icons on the RHS. (Ideally, we would not need the icon on the right, and users would be able to click on the LHS icon to check/uncheck the icon. This is currently limited by vscode APIs, and they don't have any idea on when this would be available.)
Other than this, the icons look really great. If that's not too trouble, can you make such changes on the icons, considering your proposal, so we can see better how it will look in real life?

**Comment by BarbaraAlmeida** [comment]
Sure, I can change them and test.

> My only concern with having the check/uncheck note with the box is that maybe this will make the interface a bit polluted.

I agree, that's part of why I suggested removing the lhs icons.
In the future, when its possible to click on them, it will be nice to only have them, but for now it can polute the interface and be misleading (with people trying to click on them).
Also, since all of the icons on a cathegory have the same icon they're not adding too much info.

**Comment by BarbaraAlmeida** [comment]
Test with the example set:
![annotation-testicons](https://user-images.githubusercontent.com/10374661/97507331-be476380-195b-11eb-85c0-f1f809d206fe.gif)

I will also try another set with the circles for the all-operations

**Comment by thamara** [comment]
Did some small changes. We can review this in the future.
