### ISSUE TITLE
Remove note button appears on wrong places

### ISSUE THREAD

**Issue by BarbaraAlmeida** [thamara/vscode-code-annotation#33]
The remove note button appears on the Pending and Done lines, where there is already a remove all button.
It also appear on the file line where there is no other buttons.

In both cases clicking on it doesn't do anything.
![annotation-remove](https://user-images.githubusercontent.com/10374661/97097756-61923300-1653-11eb-9a3b-6982801be170.gif)

**Comment by thamara** [comment]
That's strange. Are you using the latest version of the extension?

**Comment by BarbaraAlmeida** [comment]
It was running from my repository which was up to date to main.
But I also had an old version installed through vsix.

Removing the installed one solved the problem, looks like they were conflicting
