### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by briankohles** [thamara/vscode-code-annotation#38]
Please add a license file to indicate what this is licensed under, so I may consider it for use @ work.

My employer follows licensing very strictly without a license indicated I can't consider using it.

It would be allowed if it is a common open source (MIT, Apache, etc).

Thanks

**Comment by thamara** [comment]
Thanks for pointing that out, I forgot to include the license, but this is fixed now. The license is very permissive and should not be a problem for your use. :)
