### ISSUE TITLE
Add decoration in the code view for portions of code with annotations

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#5]
VSCode has a decoration feature that allows us to include decorations on specific portions of the code. It would be nice to have some indication of what code is included in an item on the Code Annotation extension.
Ideas on how to use it and how to show it are very welcome!

[What are decorations](https://vscode.rocks/decorations/#what-are-decorations)

**Comment by PrBart** [comment]
I am about to work on this feature.

Please, assign it to me.

**Comment by thamara** [comment]
Yay! Thanks @PrBart!
