### ISSUE TITLE
Add keybinding for adding a note

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#9]
All actions for the Extension are triggered via buttons or Command Pallete. It would be nice to have keybinding for the most common actions such as:

- Add a note
- Adding a plain note

We should also have a way of allowing users to customize it.
Any work on this direction is welcome.

**Comment by PrBart** [comment]
I'd like to do this one. Please, assign it to me.

**Comment by thamara** [comment]
Sure!

**Comment by PrBart** [comment]
@thamara i almost done the feature.
But i have no idea what exact shortcuts i have to set as default.
Maybe you have some thoughts on this matter

**Comment by thamara** [comment]
That's a hard one... I think somethink like:
Ctrl/Cmd + Shift + A -> Add note
Ctrl/Cmd + Shift + Opt + A --> Add plain note

**Comment by PrBart** [comment]
![image](https://user-images.githubusercontent.com/13170258/95028154-e1f1f380-06a6-11eb-8bf9-6a0432637da7.png)

This keybinding already taken.

And also i don't think that shortcut with more than 3 buttons is a good idea.

I think about something like: 
ctrl+alt+n -> Add note
ctrl+alt+p -> Add plain note

**Comment by thamara** [comment]
I think that's a good approach. 👍 
Ideally, the users will be capable of changing this. Not sure if this comes for free with you change so far, if not, don't worry, it can be done later.

**Comment by PrBart** [comment]
As i know all shortcuts locate at keybindings.json so you can see that user can manually edit json file or do it by Keyboard Shortcuts Settings.

So i think you may not to worry about something else besides default shortcuts.

![Screenshot_20201005_025857](https://user-images.githubusercontent.com/13170258/95030201-b7a83200-06b6-11eb-9c97-48d7dd27f48f.png)

![Screenshot_20201005_025251](https://user-images.githubusercontent.com/13170258/95030130-14571d00-06b6-11eb-9aac-d543f63dc84a.png)

**Comment by thamara** [comment]
That's really good to know. Thank you a lot!
